# ============================================================
#  FILE    : docker/Dockerfile.frontend
#  FUNGSI  : Build image Nginx untuk serve static frontend
# ============================================================

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY frontend/ /usr/share/nginx/html/
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80