# ============================================================
#  FILE    : docker/mosquitto.conf
#  FUNGSI  : Konfigurasi Mosquitto MQTT Broker
# ============================================================

# Listener TCP standar
listener 1883
protocol mqtt

# Listener WebSocket (opsional, berguna untuk MQTTX Web / browser)
listener 9001
protocol websockets

# Izinkan koneksi tanpa username/password (untuk development)
# Di production: ganti dengan password_file
allow_anonymous true

# Logging
log_type error
log_type warning
log_type notice
log_type information

# Persistence — simpan data saat container restart
persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout